dashboard/apps/pages/urls.py
from django.urls import path

import dashboard.apps.pages.facebook.views as facebookViews
import dashboard.apps.pages.instagram.views as instagramViews
import dashboard.apps.pages.twitter.views as twitterViews
import dashboard.apps.pages.mercadolibre.views as mercadoLibreAPIViews
import dashboard.apps.pages.mercadolibre_scraping.views as mercadoLibreScrapingViews
import dashboard.apps.pages.olx.views as olxViews
import dashboard.apps.pages.amazon.views as amazonViews
import dashboard.apps.pages.youtube.views as youtubeViews
import dashboard.apps.pages.google.views as googleViews
import dashboard.apps.pages.pinterest.views as pinterestViews
import dashboard.apps.frontend.views as mainViews

import dashboard.apps.pages.topic_detection.views as tdViews
import dashboard.apps.pages.data_structure_analysis.views as dSAView
import dashboard.apps.pages.clustering_results.views as cRView

import dashboard.apps.pages.kmeans.views as KMView
import dashboard.apps.pages.hcagglomerative.views as HCAView
import dashboard.apps.pages.update_db.views as DBView


app_name = 'pages'

urlpatterns = [
    path('', mainViews.IndexView.as_view(), name='index'),
    path('facebook', facebookViews.IndexView.as_view(), name='facebook'),
    path('instagram', instagramViews.IndexView.as_view(), name='instagram'),
    path('twitter', twitterViews.IndexView.as_view(), name='twitter'),
    path('twitter_resultados', twitterViews.TwitterResultados.as_view(), name='twitter_resultados'),
    path('youtube', youtubeViews.YoutubeParametros.as_view(), name='youtube'),
    path('youtube-resultados/', youtubeViews.YoutubeVideoView.as_view(), name='youtube_resultados'),
    path('youtube-resultados-comentarios/', youtubeViews.YoutubeComentariosView.as_view(),
         name='youtube_resultados_comentarios'),
    path('youtube-resultados-videos/exportar/', youtubeViews.exportarVideos, name='youtube-videos-exportar'),
    path('youtube-resultados-comentarios/exportar/', youtubeViews.exportarComentarios,
         name='youtube-comentarios-exportar'),
    path('obtener-trends', googleViews.obtenerTrends, name='obtener-trends'),
    path('obtener-trends/exportar/', googleViews.exportarTrends, name='exportar-trends'),

    path('olx', olxViews.IndexView.as_view(), name='olx'),
    path('olx-resultados', olxViews.OlxResultados.as_view(), name='olx-resultados'),

    path('amazon', amazonViews.IndexView.as_view(), name='amazon'),
    path('amazon-resultados', amazonViews.AmazonResultados.as_view(), name='amazon-resultados'),

    path('google', googleViews.IndexView.as_view(), name='google'),

    path('mercadolibre_api', mercadoLibreAPIViews.IndexView.as_view(), name='mercadolibre_api'),
    path('mercadolibre_resultados', mercadoLibreAPIViews.MercadoLibreResutlados.as_view(),
         name='mercadolibre_resultados'),

    path('mercadolibre_scraping', mercadoLibreScrapingViews.IndexView.as_view(), name='mercadolibre_scraping'),
    path('mercadolibrescraping_resultados', mercadoLibreScrapingViews.MercadoLibreResultados.as_view(),
         name='mercadolibrescraping_resultados'),

    path('pinterest', pinterestViews.IndexView.as_view(), name='pinterest'),
    path('pinterest_resultados', pinterestViews.PinterestResultados.as_view(),
         name='pinterest-resultados'),
    
    path('topic_detection', tdViews.IndexView.as_view(), name='topic_detection'),
    path('data_structure_analysis', dSAView.IndexView.as_view(), name='data_structure_analysis'),
    path('clusteringResults', cRView.IndexView.as_view(), name='clusteringResults'),
    
    path('kmeans', KMView.IndexView.as_view(), name='kmeans'),
    
    path('hcagglomerative', HCAView.IndexView.as_view(), name='hcagglomerative'),
    
    path('update_db', DBView.IndexView.as_view(), name='update_db'),
]

dashboard/apps/urls.py
from django.urls import path
from django.urls.conf import include
from dashboard.apps.frontend.views import IndexView
# from dashboard.apps.frontend.views import IndexView

app_name = 'app'

urlpatterns = [
    path('', IndexView.as_view(),	name='index'),
    path('plataforma/', include('dashboard.apps.pages.urls')),
]

dashboard/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('', include('dashboard.apps.urls')),
    path('admin/', admin.site.urls),
]

dashboard/apps/frontend/models.py
from django.db import models

# Create your models here.
# Create your models here.
class TerminoBusqueda(models.Model):
    nombre = models.CharField( max_length=50, primary_key=True)
    numero_consulta = models.IntegerField()
    def __str__(self):
        return self.nombre

dashboard/apps/pages/amazon/models.py
from django.db import models


# Create your models here.
class ProductoAmazon(models.Model):
    """
    Modelo de base datos para la plataforma Amazon
    """
    id_busqueda = models.IntegerField()
    id_producto = models.IntegerField()
    titulo = models.CharField(max_length=200)
    precio = models.CharField(max_length=20)
    ubicacion = models.CharField(max_length=50)
    descripcion = models.CharField(max_length=500)
    url = models.CharField(max_length=200)

dashboard/apps/pages/clustering_results/models.py
from django.db import models

# Create your models here.

dashboard/apps/pages/crawler/models.py
from django.db import models


# Create your models here.
class Busqueda(models.Model):
    """
    Modelo para el historial de busqueda cuando se hace un web scraping
    """
    id_busqueda = models.IntegerField()
    texto = models.CharField(max_length=100)
    fecha = models.DateField(auto_now=True)
    n_paginas = models.IntegerField()
    sitios = models.CharField(max_length=30)


class Link(models.Model):
    """
    Modelo para los links de busqueda cuando se hace un web scraping
    """
    id_busqueda = models.IntegerField()
    id_link = models.IntegerField()
    url = models.CharField(max_length=200)
    buscador = models.CharField(max_length=50)

dashboard/apps/pages/data_structure_analysis/models.py
from django.db import models

# Create your models here.

dashboard/apps/pages/hcagglomerative/models.py
from django.db import models

# Create your models here.

dashboard/apps/pages/kmeans/models.py
from django.db import models

# Create your models here.

dashboard/apps/pages/mercadolibre/models.py
from django.db import models


# Modelo de la tabla para la plataforma mercado libre
class MercadoLibre(models.Model):
    """
    Modelo para guardar los resultados de la tendencias de mercado libre
    """
    consulted_at = models.DateTimeField(auto_now=True)
    nombre = models.CharField(max_length=302, primary_key=True)
    url = models.CharField(max_length=300, default=None)

    def __str__(self):
        return self.url

dashboard/apps/pages/mercadolibre_scraping/models.py
from django.db import models


# Create your models here.
class ProductoMercadoLibre(models.Model):
    """
    Modelo para guardar datos de  mercado libre
    """
    id_busqueda = models.IntegerField()
    id_producto = models.IntegerField()
    titulo = models.CharField(max_length=200)
    precio = models.CharField(max_length=30)
    ubicacion = models.CharField(max_length=50)
    descripcion = models.CharField(max_length=500)
    url = models.CharField(max_length=200)

dashboard/apps/pages/olx/models.py
from django.db import models


# Create your models here.
class ProductoOlx(models.Model):
    """
    Modelo para guardar los resultados de olx que se hacen con web scraping
    """
    id_busqueda = models.IntegerField()
    id_producto = models.IntegerField()
    titulo = models.CharField(max_length=200)
    precio = models.CharField(max_length=200)
    ubicacion = models.CharField(max_length=50)
    descripcion = models.CharField(max_length=500)
    url = models.CharField(max_length=200)

dashboard/apps/pages/pinterest/models.py
from django.db import models
from django.conf import settings


# Create your models here.
class ProductoPinterest(models.Model):
    """
    Modelo para guardar los datos de consultas de Pinterest con web scraping
    """
    fecha_consulta = models.DateTimeField(auto_now=True)
    titulo = models.CharField(max_length=200)
    url = models.CharField(max_length=200, primary_key=True)
    descripcion = models.CharField(max_length=201)
    url_imagen = models.CharField(max_length=50)


    #retorna todos los comentarios
    @property
    def get_comentario(self):
        return ProductoPinterestComentario.objects.filter(url=self.url)


class ProductoPinterestComentario(models.Model):
    url = models.ForeignKey('ProductoPinterest', on_delete=models.CASCADE);
    comentario = models.CharField(max_length=600, primary_key=True)

dashboard/apps/pages/topic_detection/models.py
from django.db import models

# Create your models here.

dashboard/apps/pages/twitter/models.py
from django.db import models


# Create your models here.
class Tweet(models.Model):
    """
    Modelos para guardar los datos de twitter
    """
    consulted_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField()
    userName = models.CharField(max_length=200)
    isVerified = models.BooleanField()
    userFollowers_count = models.IntegerField()
    userFriends_count = models.IntegerField()
    userFavourites_count = models.IntegerField()
    userStatuses_count = models.IntegerField()
    tweet_id = models.BigIntegerField(primary_key=True)
    tweet = models.TextField()
    tweetRetweet_count = models.IntegerField()
    tweetFavorite_count = models.IntegerField()
    tweetLocation = models.TextField()

    def __str__(self):
        return self.tweet

dashboard/apps/pages/update_db/models.py
from django.db import models

# Create your models here.

dashboard/apps/pages/youtube/models.py
from django.db import models
from django.conf import settings
# Create your models here.


class YoutubeVideo(models.Model):
    videoId = models.CharField(max_length=20, primary_key=True)
    titulo = models.CharField(max_length=200)
    fechaConsulta = models.CharField(max_length=20, default=None)
    fechaPublicacion = models.CharField(max_length=20)
    numeroVistas = models.IntegerField()
    numeroDisLikes =  models.IntegerField()
    numeroLikes = models.IntegerField()
    numeroComentarios= models.IntegerField()


class YoutubeComentario(models.Model):
    videoId = models.CharField(max_length=20)
    fechaConsulta = models.CharField(max_length=20, default=None)
    fechaPublicacion = models.CharField(max_length=20)
    trend = models.CharField(max_length=20)
    comentario = models.CharField(max_length=1000)
    comentarioLikes = models.IntegerField()
    comentarioRespuestas = models.IntegerField()
    isTopLevel = models.BooleanField()

dashboard/apps/pages/mercadolibre/forms.py
from django import forms
from django.conf import settings
import tweepy
import datetime


# from django.utils.datetime_safe import datetime
class MercadoLibreForm(forms.Form):
    input_pais = forms.CharField(required=True)
    input_categoria = forms.CharField(required=True)

    def clean(self):
        cleaned_data = super().clean()
        input_pais = cleaned_data.get('input_pais')
        input_categoria = cleaned_data.get('input_categoria')

        if input_pais == 'Seleccione un Pais':
            msg = "Seleccion un pais"
            self.add_error('input_pais', msg)
        elif input_categoria == 'Seleccione una categoria':
            msg = "Seleccione un categoria"
            self.add_error('input_categoria', msg)

dashboard/apps/pages/topic_detection/forms.py
from django import forms


class TopicDetectionForm(forms.Form):
    model = forms.CharField(required=True)
    n_clusters = forms.CharField(required=True)
    

    # def clean(self):
    #     cleaned_data = super().clean()
    #     input_pais = cleaned_data.get('input_pais')
    #     input_categoria = cleaned_data.get('input_categoria')

    #     if input_pais == 'Seleccione un Pais':
    #         msg = "Seleccion un pais"
    #         self.add_error('input_pais', msg)
    #     elif input_categoria == 'Seleccione una categoria':
    #         msg = "Seleccione un categoria"
    #         self.add_error('input_categoria', msg)

dashboard/apps/pages/twitter/forms.py
import datetime

from django import forms


# from django.utils.datetime_safe import datetime
class TwitterForm(forms.Form):
    input_fecha_inicio = forms.DateField(required=True, )
    input_fecha_fin = forms.DateField(required=False)
    input_palabras_claves = forms.CharField(required=True)
    input_ubicacion = forms.CharField(required=False)
    input_idioma = forms.CharField(required=True)

    def clean_input_palabras_claves(self):
        input_palabras_claves = self.cleaned_data['input_palabras_claves'].strip()
        # do some other validation if you want...
        return input_palabras_claves

    def clean_input_ubicacion(self):
        input_ubicacion = self.cleaned_data['input_ubicacion'].strip()
        # do some other validation if you want...
        return input_ubicacion

    def clean(self):
        cleaned_data = super().clean()
        input_fecha_inicio = cleaned_data.get('input_fecha_inicio')
        input_fecha_fin = cleaned_data.get('input_fecha_fin')
        if (input_fecha_inicio is not None) and (input_fecha_fin is not None):
            if input_fecha_inicio > datetime.date.today():
                msg = "La fecha no puede ser  mayor a la de hoy"
                self.add_error('input_fecha_inicio', msg)
            elif input_fecha_fin > datetime.date.today():
                msg = "La fecha no puede ser  mayor a la de hoy"
                self.add_error('input_fecha_fin', msg)

            elif input_fecha_inicio == input_fecha_fin:
                msg = "No pueden ser fechas iguales"
                self.add_error('input_fecha_inicio', msg)
                self.add_error('input_fecha_fin', msg)

            elif input_fecha_inicio > input_fecha_fin:
                msg = "Fecha inicio no puede ser mayor la fecha final."
                self.add_error('input_fecha_inicio', msg)

dashboard/apps/pages/youtube/forms.py
from django import forms

class YoutubeVideoForm(forms.Form):
    palabrasClave = forms.CharField(required=True)
    fecha = forms.DateTimeField(required=True)
    region = forms.CharField(required=True)

class YoutubeCommentForm(forms.Form):
    videoId = forms.CharField(required=True)

dashboard/templates/site/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
	<meta name="description" content="" />
	<meta name="author" content="" />

	<!-- incio cache -->
{#	<meta http-equiv="Expires" content="0">#}
{#	<meta http-equiv="Last-Modified" content="0">#}
{#	<meta http-equiv="Cache-Control" content="no-cache, mustrevalidate">#}
{#	<meta http-equiv="Pragma" content="no-cache">#}
{#	<!-- fin cache -->#}

	<title>
		{% block title %}
		Dashboard Extracción de Datos
		{% endblock title %}
	</title>

	{% include 'site/base_header_styles.html' %}
	{% block    extra_styles %}
	{% endblock extra_styles %}

</head>

<body id="page-top">

	<div id="wrapper">
		<!-- Sidebar -->
		<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
			<!-- Sidebar - Brand -->
			<a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'app:index' %}">
				<div class="sidebar-brand-icon rotate-n-15">
					<i class="fas fa-database"></i>
				</div>
				<div class="sidebar-brand-text mx-3"> Proyecto Suma</div>
			</a>

			<!-- Divider -->
			<hr class="sidebar-divider my-0" />

			<!-- Nav Item - Dashboard -->
			<li class="nav-item active">
				<a class="nav-link" href="{% url 'app:index' %}">
					<i class="fas fa-fw fa-tachometer-alt"></i>
					<span>Dashboard</span></a>
			</li>

			<!-- Divider -->
			<hr class="sidebar-divider" />

			<!-- Heading -->
			<div class="sidebar-heading">
				Redes Sociales
			</div>

			<!-- Nav Item - Facebook -->
			<li class="nav-item">
				<a class="nav-link" href="{% url 'app:pages:facebook' %}">
					<i class="fab fa-facebook-square"></i>
					<span>Facebook</span></a>
			</li>

			<!-- Nav Item - Instagram -->
			<li class="nav-item">
				<a class="nav-link" href="{% url 'app:pages:instagram' %}">
					<i class="fab fa-instagram"></i>
					<span>Instagram</span></a>
			</li>

			<!-- Nav Item - Twitter -->
			<li class="nav-item">
				<a class="nav-link" href="{% url 'app:pages:twitter' %}">
					<i class="fab fa-twitter"></i>
					<span>Twitter</span></a>
			</li>
			<!-- Nav Item - Youtube -->
			<li class="nav-item">
				<a class="nav-link" href="{% url 'app:pages:youtube' %}">
					<i class="fab fa-youtube"></i>
					<span>Youtube</span></a>
			</li>

			<!-- Nav Item - Google -->
			<li class="nav-item">
				<a class="nav-link" href="{% url 'app:pages:google' %}">
					<i class="fab fa-google"></i>
					<span>Google</span></a>
			</li>
			<!-- Divider -->
			<hr class="sidebar-divider" />

			<!-- Heading -->
			<div class="sidebar-heading">
				Plataformas E-commerce
			</div>

			<!-- Nav Item - Mercado Libre -->
			<li class="nav-item">
					<a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
						<i class="fas fa-shopping-cart"></i>
						<span>Mercado Libre</span>
					</a>
					<div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
						<div class="bg-white py-2 collapse-inner rounded">
							<a href="{% url 'app:pages:mercadolibre_api' %}" class="collapse-item" >API</a>
							<a href="{% url 'app:pages:mercadolibre_scraping' %}" class="collapse-item" >Web Scraping</a>
						</div>
					</div>
				</li>

			<!-- Nav Item - OLX -->
			<li class="nav-item">
				<a class="nav-link" href="{% url 'app:pages:olx' %}">
					<i class="fas fa-fw fa-chart-area"></i>
					<span>OLX</span></a>
			</li>
            <!-- Nav Item - Amazon -->
			<li class="nav-item">
				<a class="nav-link" href="{% url 'app:pages:amazon' %}">
					<i class="fab fa-amazon"></i>
					<span>Amazon</span></a>
			</li>

            <!-- Nav Item - Pinterest -->
			<li class="nav-item">
				<a class="nav-link" href="{% url 'app:pages:pinterest' %}">
					<i class="fab fa-pinterest-square"></i>
					<span>Pinterest</span></a>
			</li>

			<!-- Divider -->
			<hr class="sidebar-divider" />

			<!-- Heading -->
			<div class="sidebar-heading">
				Detección de temas
			</div>

			<!-- Nav Item - Topic Detection -->
			<li class="nav-item">
					<a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseThree" aria-expanded="true" aria-controls="collapseThree">
						<i class="fas fa-search"></i>
						<span>Hot Topics</span>
					</a>
					<div id="collapseThree" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
						<div class="bg-white py-2 collapse-inner rounded">
							<a href="{% url 'app:pages:data_structure_analysis' %}" class="collapse-item" >Estructura de datos</a>
							<a class="collapse-item" >Detección</a>

							<div id="collapseThree" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
													<div class="bg-white py-2 collapse-inner rounded">
														<a href="{% url 'app:pages:kmeans' %}" class="collapse-item" >K-Means</a>
														<a href="{% url 'app:pages:hcagglomerative' %}" class="collapse-item" >H.C. - Agglomerative</a>
													</div>
												</div>



							<a href="{% url 'app:pages:clusteringResults' %}" class="collapse-item" >Resultados</a>

							<a href="{% url 'app:pages:update_db' %}" class="collapse-item" >Actualizar DB</a>

						</div>
					</div>
				</li>


				


			<!-- Divider -->
			<hr class="sidebar-divider d-none d-md-block" />

			<!-- Sidebar Toggler (Sidebar) -->
			<div class="text-center d-none d-md-inline">
				<button class="rounded-circle border-0" id="sidebarToggle"></button>
			</div>
		</ul>
		<!-- End of Sidebar -->

		<!-- Content Wrapper -->
		<div id="content-wrapper" class="d-flex flex-column">
			<nav class="navbar navbar-light bg-white topbar mb-3 static-top shadow  justify-content-center font-weight-bold">
			Universidad de Cuenca
			</nav>
			<!-- Main Content -->
			<div id="content">
				<!-- Begin Page Content -->
				{% block content %}
				MISSING CONTENT
				{% endblock content %}
				<!-- /.container-fluid -->
			</div>
			<!-- End of Main Content -->

			<!-- Footer -->
			<footer class="sticky-footer bg-white">
				<div class="container my-auto">
					<div class="copyright text-center my-auto">
						<span>Copyright &copy; 2020</span>
					</div>
				</div>
			</footer>
			<!-- End of Footer -->
		</div>
		<!-- End of Content Wrapper -->
	</div>
	<!-- End of Page Wrapper -->

	{% include 'site/base_footer_scripts.html' %}
	{%  block extraScripts %}
	{% endblock extraScripts %}
</body>

</html>

dashboard/templates/site/base_footer_scripts.html
{% load static %}

<script src="{% static 'vendor/popper/2.0.6/js/popper.min.js' %}"></script>
<script src="{% static 'vendor/jquery/3.4.1/js/jquery.min.js' %}"></script>
<script src="{% static 'vendor/jquery-easing/1.4.1/js/jquery.easing.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/4.4.1/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'vendor/chart/2.8.0/js/Chart.js' %}"></script>
<script src="{% static 'vendor/sb-admin-2/js/sb-admin-2.js' %}"></script>
<script src="{% static 'site/js/site.js' %}"></script>

dashboard/templates/site/base_header_styles.html
{% load static %}
<!-- iconos -->
<link href="{% static 'vendor/fontawesome-free/5.9.0/css/all.min.css' %}" rel="stylesheet" type="text/css" />

{#<link#}
{#    href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"#}
{#    rel="stylesheet" />#}

<link href="{% static 'vendor/sb-admin-2/css/sb-admin-2.min.css' %}" rel="stylesheet" type="text/css" />

<link href="{% static 'vendor/datatables/1.10.20/datatables.bs4.min.css' %}" rel="stylesheet" type="text/css" />